import sys
import os

# ------------------------------------------------------------------
# Ovaj fajl ne menjati, da bi automatsko ocenjivanje bilo moguce
if len(sys.argv) > 1:
    DATASET_PATH = sys.argv[1]
else:
    DATASET_PATH = '.' + os.path.sep + 'dataset' + os.path.sep + 'train' + os.path.sep
# ------------------------------------------------------------------

labeled_samples = dict()

with open(DATASET_PATH+'annotations.csv') as file:
    data = file.read()
    lines = data.split('\n')
    for index, line in enumerate(lines):
        cols = line.split(';')
        if (cols and cols[0] == '') or cols[0] == 'Image':
            continue
        cols[0] = cols[0].replace('\r', '')
        cols[1] = cols[1].replace('\r', '')
        cols[2] = cols[2].replace('\r', '')
        cols[3] = cols[3].replace('\r', '').lower()
        labeled_samples[cols[0]] = [float(cols[1]), float(cols[2]), cols[3]]


# read results file generated by the main.py
results = dict()

with open('result.csv') as file:
    data = file.read()
    lines = data.split('\n')
    for index, line in enumerate(lines):
        cols = line.split(',')
        if cols and cols[0] == '':
            continue
        cols[0] = cols[0].replace('\r', '')
        cols[1] = cols[1].replace('\r', '')
        cols[2] = cols[2].replace('\r', '')
        cols[3] = cols[3].replace('\r', '').lower()
        results[cols[0]] = [float(cols[1]), float(cols[2]), cols[3]]


# evaluate how results file matches the labelled samples
percentage_red_cells = 0
for labeled_image_name in labeled_samples:
    if results[labeled_image_name][0] == 0:
        continue
    diff = abs(labeled_samples[labeled_image_name][0] - results[labeled_image_name][0])
    if diff == 0:
        percentage_red_cells += 100.0
    else:
        percentage_red_cells += 100.0/(diff+1)
percentage_red_cells /= len(labeled_samples)


percentage_white_cells = 0
for labeled_image_name in labeled_samples:
    if results[labeled_image_name][1] == 0:
        continue
    diff = abs(labeled_samples[labeled_image_name][1] - results[labeled_image_name][1])
    if diff == 0:
        percentage_white_cells += 100.0
    else:
        percentage_white_cells += 100.0/(diff+1)
percentage_white_cells /= len(labeled_samples)


percentage_diagnosis = 0
for labeled_image_name in labeled_samples:
    if labeled_samples[labeled_image_name][2] == results[labeled_image_name][2]:
        percentage_diagnosis += 100.0
percentage_diagnosis /= len(labeled_samples)

print(percentage_red_cells*0.5+percentage_white_cells*0.3+percentage_diagnosis*0.2)
