import csv
import datetime

from fuzzywuzzy import fuzz
import sys
import os

# ------------------------------------------------------------------
# Ovaj fajl ne menjati, da bi automatsko ocenjivanje bilo moguce
from process import Person

if len(sys.argv) > 1:
    VALIDATION_DATASET_PATH = sys.argv[1]
else:
    VALIDATION_DATASET_PATH = os.path.join(os.path.dirname(__file__), 'dataset', 'validation')

if len(sys.argv) > 2:
    MODELS_FOLDER = sys.argv[2]
else:
    MODELS_FOLDER = os.path.join(os.path.dirname(__file__), 'models')
# ------------------------------------------------------------------

ground_truth = {}

with open(os.path.join(VALIDATION_DATASET_PATH, 'annotations.csv')) as file:
    reader = csv.DictReader(file,
                            fieldnames=['file_name', 'name', 'company', 'date_of_birth', 'job',
                                        'social_security_number'],
                            quoting=csv.QUOTE_ALL, delimiter=',', quotechar='"')

    next(reader)
    for row in reader:
        person = Person(
            name=row['name'],
            company=row['company'],
            date_of_birth=datetime.datetime.strptime(row['date_of_birth'], '%Y-%m-%d').date(),
            job=row['job'],
            ssn=row['social_security_number']
        )
        ground_truth[row['file_name']] = person


# read results file generated by the main.py
extracted_data = {}

with open('result.csv', 'r') as file:
    reader = csv.DictReader(file,
                            fieldnames=['file_name', 'name', 'company', 'date_of_birth', 'job',
                                        'social_security_number'],
                            quoting=csv.QUOTE_ALL, delimiter=',', quotechar='"')

    next(reader)
    for row in reader:
        person = Person(
            name=row['name'],
            company=row['company'],
            date_of_birth=datetime.datetime.strptime(row['date_of_birth'], '%Y-%m-%d').date(),
            job=row['job'],
            ssn=row['social_security_number']
        )
        extracted_data[row['file_name']] = person

total_samples = len(ground_truth)

name_hits = 0
company_hits = 0
dob_hits = 0
job_hits = 0
ssn_hits = 0

for file_name in extracted_data.keys():
    extracted_person = extracted_data[file_name]
    truth_person = ground_truth[file_name]

    name_hits += fuzz.ratio(truth_person.name, extracted_person.name) / 100
    company_hits += extracted_person.company == truth_person.company
    dob_hits += extracted_person.date_of_birth == truth_person.date_of_birth
    job_hits += fuzz.ratio(truth_person.job, extracted_person.job) / 100
    ssn_hits += fuzz.ratio(truth_person.ssn, extracted_person.ssn) / 100

total = sum([name_hits, company_hits, dob_hits, job_hits, ssn_hits]) / (total_samples * 5)

print(total * 100)
